language: clojure 
lein: lein
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
  fast_finish: true
cache: cargo
script: lein do clean, test
jdk: 
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - openjdk8
  - openjdk10
branches:
  only:
    - master
